### ISSUE TITLE
Mali device driver does not respond properly to rockchip version check

### ISSUE THREAD

**Issue by st1905** [libhybris/libhybris#229]
W/libEGL  (21081): eglInitialize(0x1) failed (EGL_BAD_ALLOC)
D/libEGL  (21097): loaded /system/lib/egl/libEGL_mali.so
D/libEGL  (21097): loaded /system/lib/egl/libGLESv1_CM_mali.so
D/libEGL  (21097): loaded /system/lib/egl/libGLESv2_mali.so
E/        (21097): Mali device driver does not respond properly to rockchip version check
W/libEGL  (21097): eglInitialize(0x1) failed (EGL_BAD_ALLOC)

I have compiled jelly bean source and extracted headers and system then built libhybris but when i try to run the tests, this is what it says...

**Comment by FlorentRevest** [comment]
I've been facing the same problem for several days with a radxa rock board. Has any workaround been found since then ?

**Comment by st1905** [comment]
Workaround is to use mali kernel module for the sources you compile for libhybris, if the running system has a different version mali kernel module from the sources you compiled, that mismatch will happen.

**Comment by FlorentRevest** [comment]
Indeed I found that this version mismatch causes the first issue "Mali device driver does not respond properly to rockchip version check", but what about the last error you got:

    E/EGL-ERROR: mali_surface __egl_platform_create_surface_from_native_buffer(android_native_buffer_t, egl_surface, mali_base_ctx_handle):556: invalid buffer handle given (0x414c72c8)
    E/EGL-ERROR: void __egl_platform_dequeue_buffer(egl_surface*):1433: Failed to create a surface from native buffer (0x414c71bc)
    E/libEGL ( 1995): eglMakeCurrent:599 error 3003 (EGL_BAD_ALLOC)

I also get those lines when I use the correct mali.ko and ump.ko. When I load test_egl I get a black screen for a second and this error in the logs.

In the meantime, thank you for your attention and your help!

**Comment by st1905** [comment]
You`re welcome. That`s where i got stuck, exactly the same thing happened, flashing black screen and the error, you may get some help from the odroid forum, they have their workaround for odroid based devices.

**Comment by FlorentRevest** [comment]
Alright, I'll take a look at it and I won't forget to let a message here if I find a solution.

**Comment by FlorentRevest** [comment]
I finally found the solution: I used strace to debug the syscalls of test_glesv2 and I noticed that it was trying to open /system/lib/hw/gralloc.rk31sdk.so which doesn't exist. So it opened /system/lib/hw/gralloc.default.so which doesn't give the expected buffer to mali and ump and causes the error.

I replaced the "rk31sdk" occurences in /system/build.prop by "rk30board" so that now it opens the correct gralloc... And now it works! https://www.dropbox.com/s/7gft528a5b9k663/VID_20150329_144218.mp4?dl=0

Thank you for the informations you gave and I guess you can close this issue, the solution was a wrong gralloc module.

**Comment by st1905** [comment]
Thank you for the update, thats great news!
